apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head>
      <title>Kubernetes ConfigMap Demo</title>
    </head>
    <body>
      <h1>Hello from ConfigMap! 🎉</h1>
      <p>This page is being served by Nginx with content mounted from a Kubernetes ConfigMap.</p>
    </body>
    </html>
