apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: test-container
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          env:
            - name: USER_NAME_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: dev-config
                  key: user_name
            - name: USER_INITIAL_VARIABLE
              valueFrom:
                configMapKeyRef:
                  name: dev-config
                  key: user_initial

